version: "3.8"

services:
  app:
    container_name: google-keep
    image: google-keep
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
